# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"space_adder": "11_transforms.sequence.ipynb",
         "SpaceTransform": "11_transforms.sequence.ipynb",
         "HFTokenizerWrapper": "11_transforms.sequence.ipynb"}

modules = ["transforms/sequence.py"]

doc_url = "https://judowill.github.io/justenough/"

git_url = "https://github.com/judowill/justenough/tree/main/"

def custom_doc_links(name): return None
