# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"masked_concat_pool": "01_models.glp.ipynb",
         "MaskedConcatPooling": "01_models.glp.ipynb",
         "model_mask_pooling": "01_models.glp.ipynb",
         "space_adder": "11_transforms.sequence.ipynb",
         "SpaceTransform": "11_transforms.sequence.ipynb",
         "HFTokenizerWrapper": "11_transforms.sequence.ipynb",
         "HFPoolingTransform": "11_transforms.sequence.ipynb",
         "HFBertDataLoaders": "12_transforms.dataloaders.ipynb"}

modules = ["models/glp.py",
           "transforms/sequence.py",
           "transforms/dataloaders.py"]

doc_url = "https://judowill.github.io/justenough/"

git_url = "https://github.com/judowill/justenough/tree/main/"

def custom_doc_links(name): return None
